In [1]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\alumnos\appdata\roaming\python\python314\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\alumnos\appdata\roaming\python\python314\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alumnos\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\alumnos\appdata\roaming\python\python314\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\alumnos\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\alumnos\appdata\roaming\python\python314\site-packages (2.4.4)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np

In [6]:
#Generar DataFrame desde un diccionario
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sofia'],
    'Edad': [23, 25, 30, 32],
    'Ciudad': ['Santiago', 'Talca', 'Temuco', 'Santiago']
}

print(type(data))

<class 'dict'>

In [8]:
df = pd.DataFrame(data)
print(type(df))

<class 'pandas.DataFrame'>

In [17]:
df.head()

   Nombre  Edad    Ciudad
0     Ana    23  Santiago
1    Luis    25     Talca
2  Carlos    30    Temuco
3   Sofia    32  Santiago

In [13]:
df.tail(2)

   Nombre  Edad    Ciudad
2  Carlos    30    Temuco
3   Sofia    32  Santiago

In [11]:
df['Nombre']

0       Ana
1      Luis
2    Carlos
3     Sofia
Name: Nombre, dtype: str

In [ ]:
df.loc[:, ['Nombre' , 'Edad']] #Seleccionar por etiqueta

   Nombre  Edad
0     Ana    23
1    Luis    25
2  Carlos    30
3   Sofia    32

In [16]:
df.iloc[1, 2]

'Talca'

In [21]:
#Cambiar datos
df2 = df.copy()

In [23]:
df2.loc[2, 'Edad'] = 99
print(df2)

   Nombre  Edad    Ciudad
0     Ana    23  Santiago
1    Luis    25     Talca
2  Carlos    99    Temuco
3   Sofia    32  Santiago

In [24]:
df2.iloc[3, 2] = 'Concepcion'
print(df2)

   Nombre  Edad      Ciudad
0     Ana    23    Santiago
1    Luis    25       Talca
2  Carlos    99      Temuco
3   Sofia    32  Concepcion

In [25]:
df2['Ciudad'] = 'Conce'
print(df2)

   Nombre  Edad Ciudad
0     Ana    23  Conce
1    Luis    25  Conce
2  Carlos    99  Conce
3   Sofia    32  Conce

In [38]:
df2['Edad2'] = df2['Edad']*2
print(df2)

   Nombre  Edad Estado  Edad2
0     Ana    23  Conce     46
1    Luis    25  Conce     50
2  Carlos    99  Conce    198
3   Sofia    32  Conce     64

In [39]:
#editar y eliminar columnas 
df2.rename(columns = {'Ciudad': 'Estado'}, inplace=True)
print(df2)

   Nombre  Edad Estado  Edad2
0     Ana    23  Conce     46
1    Luis    25  Conce     50
2  Carlos    99  Conce    198
3   Sofia    32  Conce     64

In [40]:
df2.drop(columns = ['Edad2'], inplace=True)
print(df2)

   Nombre  Edad Estado
0     Ana    23  Conce
1    Luis    25  Conce
2  Carlos    99  Conce
3   Sofia    32  Conce

In [41]:
#Descripcion de DF
df3 = df.copy()
df3.describe()

            Edad
count   4.000000
mean   27.500000
std     4.203173
min    23.000000
25%    24.500000
50%    27.500000
75%    30.500000
max    32.000000

In [42]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  4 non-null      str
 1   Edad    4 non-null      int64
 2   Ciudad  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [43]:
len(df3)

4

In [47]:
df3['Edad'].mean()
print(df3['Edad'].max())

32

In [52]:
df3['Edad'].value_counts()

Edad
32    1
Name: count, dtype: int64

In [53]:
df4 = df.copy()

In [49]:
df3['Edad'].nunique()

4

In [50]:
#Filtrado de datos
df3 = df3[df3['Ciudad'] == 'Santiago']
print(df3)

  Nombre  Edad    Ciudad
0    Ana    23  Santiago
3  Sofia    32  Santiago

In [51]:
df3 = df3[df3['Edad'] >= 24]
print(df3)

  Nombre  Edad    Ciudad
3  Sofia    32  Santiago

In [55]:
df4 = df4[(df4['Ciudad'] == 'Santiago') & (df4['Edad'] >= 24)]
print(df4)

  Nombre  Edad    Ciudad
3  Sofia    32  Santiago

In [ ]:
# and es '&'
# or es '|'
# not es '~'